"""empty message

Revision ID: 10c00d7ea6f2
Revises: 6f65a4beaadd
Create Date: 2016-04-29 23:32:55.966525

"""

# revision identifiers, used by Alembic.
revision = '10c00d7ea6f2'
down_revision = '6f65a4beaadd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('is_notice', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_date_id'], ['meal_date.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    ### end Alembic commands ###
