"""empty message

Revision ID: 41a3d77253df
Revises: da43e11fedc8
Create Date: 2016-04-25 22:00:03.143978

"""

# revision identifiers, used by Alembic.
revision = '41a3d77253df'
down_revision = 'da43e11fedc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_date_relation',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('meal_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_date_id'], ['meal_date.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_date_relation')
    ### end Alembic commands ###
