"""empty message

Revision ID: 4eb676103648
Revises: 7dd3bfabb2a3
Create Date: 2016-06-14 23:27:07.459009

"""

# revision identifiers, used by Alembic.
revision = '4eb676103648'
down_revision = '7dd3bfabb2a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('korean', 'western', 'soup', 'pork', 'beef', 'chinese', 'noodle'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_category',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('is_notice', sa.Boolean(), nullable=True),
    sa.Column('is_chair', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_store_relation',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_comment',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'menu', sa.Column('price', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'menu', 'price')
    op.drop_table('store_comment')
    op.drop_table('menu_store_relation')
    op.drop_table('board_category')
    op.drop_table('store')
    ### end Alembic commands ###
