"""empty message

Revision ID: 607e026379c5
Revises: 10c00d7ea6f2
Create Date: 2016-05-09 21:44:50.793740

"""

# revision identifiers, used by Alembic.
revision = '607e026379c5'
down_revision = '10c00d7ea6f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('sex', sa.Enum('male', 'female'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'birth')
    ### end Alembic commands ###
