"""empty message

Revision ID: 6f65a4beaadd
Revises: 41a3d77253df
Create Date: 2016-04-25 23:10:29.354860

"""

# revision identifiers, used by Alembic.
revision = '6f65a4beaadd'
down_revision = '41a3d77253df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_date_id'], ['meal_date.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    ### end Alembic commands ###
