"""empty message

Revision ID: 7dd3bfabb2a3
Revises: e10d35b44c84
Create Date: 2016-05-25 23:08:45.951300

"""

# revision identifiers, used by Alembic.
revision = '7dd3bfabb2a3'
down_revision = 'e10d35b44c84'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'category',
               existing_type=mysql.ENUM(u'noodle', u'salad', u'takeout', u'korean', u'western', u'dinner', u'dinner-noodle'),
               nullable=False)
    op.alter_column('meal', 'time',
               existing_type=mysql.ENUM(u'morning', u'lunch', u'dinner'),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'time',
               existing_type=mysql.ENUM(u'morning', u'lunch', u'dinner'),
               nullable=True)
    op.alter_column('meal', 'category',
               existing_type=mysql.ENUM(u'noodle', u'salad', u'takeout', u'korean', u'western', u'dinner', u'dinner-noodle'),
               nullable=True)
    ### end Alembic commands ###
