"""empty message

Revision ID: e10d35b44c84
Revises: 607e026379c5
Create Date: 2016-05-09 23:30:08.151101

"""

# revision identifiers, used by Alembic.
revision = 'e10d35b44c84'
down_revision = '607e026379c5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Enum('male', 'female'), nullable=True))
    op.drop_column('user', 'sex')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', mysql.ENUM(u'male', u'female'), nullable=True))
    op.drop_column('user', 'gender')
    ### end Alembic commands ###
